### ISSUE TITLE
Little confused why this was made

### ISSUE THREAD

**Issue by AppleTechy** [chanomie/homebridge-myq#1]
What is the difference between this and nfarina's MYQ plugin?

**Comment by chanomie** [comment]
What's the link to nfarina's?  Probably I made a duplicate and can kill this project - but when I was searching on npmjs for Chamberlain and MyQ I didn't find anything.

**Comment by AppleTechy** [comment]
Search for LiftMaster. Both LiftMaster and Chamberlain use the same
server/tech the gui to access just say LiftMaster vs Chamberlain. So it
won't make a difference. I have a chamberlain garage door opener and I run
the LiftMaster plugin just fine

**Comment by chado99** [comment]
so, what was the result--is this redundant? Can we just use lift master?

**Comment by AppleTechy** [comment]
Yes this plugin is redundant. I would just use the LiftMaster plugin as
that is what I am doing and it works just fine connecting to chamberlain
garage doors

**Comment by chanomie** [comment]
Yes. Dead project. I removed from npm.

**Comment by techortreat** [comment]
hi  - I am struggling to get my chamberlain garage opener to work. Got confused with the whether to use MYQ or lift master. Sorry  - I am just following instructions on the various sites and do not understand the detailed logic.
Can someone who has a chamberlain opener please help?
What should be in the config.json file?
What app should be used on the iPhone - Chamberlain or Liftmaster?
After adding homebridge accessory to my phone using the code - what is the next step? 
Thanks in advance!

**Comment by AppleTechy** [comment]
Use the Liftmaster plugin. The reason it works it both Chamberlain and
Liftmaster use the same MYQ servers. And the Liftmaster plugin with
developed first and has been developed more than the other plugins. As for
should be in the Config.json read the readme text file and it explains what
is needed. As for what HomeKit App it is up to you. I personal use
"Hesperus" developed by our very one @khaost but there are many you can
choose from,it's just personal preference.

**Comment by techortreat** [comment]
Thanks. I tried using the Liftmaster plugin with the config.json mentioned in the readme and  it didn't seem to work.  When using siri it says "sorry - I wasn't able to find any garage doors at this time".
This is the config.json
{
    "bridge": {
        "name": "Homebridge",
        "username": "CC:22:3D:E3:CE:30",
        "port": 51826,
        "pin": "031-45-154"
    },
    "platforms": [{}],
    "accessories": [{
        "accessory": "LiftMaster",
        "name": "Garage Door",
        "username": "**_**@__.com",
        "password": "_**"
    }]
}

when I run homebridge on the raspberry pi - these are the messages.

**\* WARNING **\* The program 'nodejs' uses the Apple Bonjour compatibility layer of Avahi.
**\* WARNING **\* Please fix your application to use the native API of Avahi!
**\* WARNING **\* For more information see http://0pointer.de/avahi-compat?s=libdns_sd&e=nodejs
**\* WARNING **\* The program 'nodejs' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
**\* WARNING **\* Please fix your application to use the native API of Avahi!
**\* WARNING **\* For more information see http://0pointer.de/avahi-compat?s=libdns_sd&e=nodejs&f=DNSServiceRegister
[8/15/2016, 11:19:39 PM] Loaded plugin: homebridge-liftmaster
[8/15/2016, 11:19:39 PM] Registering accessory 'homebridge-liftmaster.LiftMaster'
[8/15/2016, 11:19:39 PM] ---
Scan this code with your HomeKit App on your iOS device to pair with Homebridge:

```
┌────────────┐     
│ 031-45-154 │     
└────────────┘     
```

[8/15/2016, 11:19:39 PM] Homebridge is running on port 51826.

**Comment by techortreat** [comment]
is there information I need to add in the "platform section" in the config file?  I already have Chamberlain app running and controlling my garage door.  I added homebridge as an accessory using the apple HMCatalog app. Besides adding it to the app, is there any other steps I am missing?
